version: '3'
services:
  db:
    image: mysql:5.6.50
    environment:
      MYSQL_DATABASE: mysql_rails_app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tasq
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true  
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local 
